[package]
name = "selection_sort_vec"
version = "0.1.0"
authors = ["Andrii Nyzhnyk <andrij1510@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
